module RgssTk
  module EventCommandParameterCodes
    VARIABLE_OPERATION_SET = 0
    VARIABLE_OPERATION_ADD = 1
    VARIABLE_OPERATION_SUB = 2
    VARIABLE_OPERATION_MUL = 3
    VARIABLE_OPERATION_DIV = 4
    VARIABLE_OPERATION_MOD = 5

    VARIABLE_OPERAND_TYPE_INT       = 0
    VARIABLE_OPERAND_TYPE_VARIABLE  = 1
    VARIABLE_OPERAND_TYPE_RANDOM    = 2
    VARIABLE_OPERAND_TYPE_GAME_DATA = 3
    VARIABLE_OPERAND_TYPE_SCRIPT    = 4

    LOCATION_INFO_TERRAIN_TAG = 0
    LOCATION_INFO_EVENT_ID    = 1
    LOCATION_INFO_TILE_ID     = 2
    LOCATION_INFO_TILE_ID_1   = 2
    LOCATION_INFO_TILE_ID_2   = 3
    LOCATION_INFO_TILE_ID_3   = 4
    LOCATION_INFO_REGION_ID   = 5

    CONDITIONAL_VARIABLE_OPERATOR_EQUAL              = 0
    CONDITIONAL_VARIABLE_OPERATOR_GREATER_THAN_EQUAL = 1
    CONDITIONAL_VARIABLE_OPERATOR_LESS_THAN_EQUAL    = 2
    CONDITIONAL_VARIABLE_OPERATOR_GREATER_THAN       = 3
    CONDITIONAL_VARIABLE_OPERATOR_LESS_THAN          = 4
    CONDITIONAL_VARIABLE_OPERATOR_NOT_EQUAL          = 5

    CONDITIONAL_BRANCH_TYPE_SWITCH = 0
    CONDITIONAL_BRANCH_TYPE_VARIABLE = 1
    CONDITIONAL_BRANCH_TYPE_SELF_SWITCH = 2
    CONDITIONAL_BRANCH_TYPE_TIMER = 3
    CONDITIONAL_BRANCH_TYPE_ACTOR = 4
    CONDITIONAL_BRANCH_TYPE_ENEMY = 5
    CONDITIONAL_BRANCH_TYPE_CHARACTER = 6
    CONDITIONAL_BRANCH_TYPE_GOLD = 7
    CONDITIONAL_BRANCH_TYPE_ITEM = 8
    CONDITIONAL_BRANCH_TYPE_WEAPON = 9
    CONDITIONAL_BRANCH_TYPE_ARMOR = 10
    CONDITIONAL_BRANCH_TYPE_BUTTON = 11
    CONDITIONAL_BRANCH_TYPE_SCRIPT = 12
    CONDITIONAL_BRANCH_TYPE_VEHICLE = 13

    CONDITIONAL_BRANCH_TYPE_HASH_ = {
      switch: CONDITIONAL_BRANCH_TYPE_SWITCH,
      variable: CONDITIONAL_BRANCH_TYPE_VARIABLE,
      self_switch: CONDITIONAL_BRANCH_TYPE_SELF_SWITCH,
      timer: CONDITIONAL_BRANCH_TYPE_TIMER,
      actor: CONDITIONAL_BRANCH_TYPE_ACTOR,
      enemy: CONDITIONAL_BRANCH_TYPE_ENEMY,
      character: CONDITIONAL_BRANCH_TYPE_CHARACTER,
      gold: CONDITIONAL_BRANCH_TYPE_GOLD,
      item: CONDITIONAL_BRANCH_TYPE_ITEM,
      weapon: CONDITIONAL_BRANCH_TYPE_WEAPON,
      armor: CONDITIONAL_BRANCH_TYPE_ARMOR,
      button: CONDITIONAL_BRANCH_TYPE_BUTTON,
      script: CONDITIONAL_BRANCH_TYPE_SCRIPT,
      vehicle: CONDITIONAL_BRANCH_TYPE_VEHICLE
    }
  end
end
